import { ArrowUpFromLine, ChevronDown, CircleHelp, Command as CommandIcon, FilePlus2, FolderOpen, Moon, Redo2, Save, Sparkles, Sun, Undo2 } from 'lucide-react';
import type { ReactNode } from 'react';
import type { ThemeMode } from '../store/useWorkspaceStore';

type MenuItem = { label: string; shortcut?: string; disabled?: boolean; onClick: () => void };
type TopMenuBarProps = { projectName: string; dirty: boolean; theme: ThemeMode; activeMenu: string | null; onMenu: (menu: string | null) => void; onNew: () => void; onOpen: () => void; onSave: () => void; onSaveAs: () => void; onUndo: () => void; onRedo: () => void; onDuplicate: () => void; onCommandPalette: () => void; onToggleGrid: () => void; onToggleNavigator: () => void; onToggleInspector: () => void; onFit: () => void; onAlign: () => void; onExportSvg: () => void; onAbout: () => void; onTheme: () => void };

export function TopMenuBar({ projectName, dirty, theme, activeMenu, onMenu, onNew, onOpen, onSave, onSaveAs, onUndo, onRedo, onDuplicate, onCommandPalette, onToggleGrid, onToggleNavigator, onToggleInspector, onFit, onAlign, onExportSvg, onAbout, onTheme }: TopMenuBarProps) {
  const menu = (label: string, items: MenuItem[], icon?: ReactNode) => <div className="menu-group"><button className={`menu-trigger ${activeMenu === label ? 'active' : ''}`} onClick={() => onMenu(activeMenu === label ? null : label)}>{icon}{label}<ChevronDown size={11} /></button>{activeMenu === label && <div className="menu-popover">{items.map((item) => <button key={item.label} disabled={item.disabled} onClick={() => { item.onClick(); onMenu(null); }}><span>{item.label}</span>{item.shortcut && <kbd>{item.shortcut}</kbd>}</button>)}</div>}</div>;
  return <header className="topbar redesign-topbar">
    <div className="topbar-title"><div className="brand-mark small">U</div><div className="product-lockup"><strong>UML Studio</strong><span>Local modeler</span></div><span className="topbar-divider" /><span className="project-title">{projectName}{dirty && <span className="dirty-dot" title="Unsaved changes" />}</span></div>
    <div className="menu-strip">{menu('File', [{ label: 'New project', shortcut: 'Ctrl+N', onClick: onNew }, { label: 'Open project', shortcut: 'Ctrl+O', onClick: onOpen }, { label: 'Save project', shortcut: 'Ctrl+S', onClick: onSave }, { label: 'Save As…', onClick: onSaveAs }])}{menu('Edit', [{ label: 'Undo', shortcut: 'Ctrl+Z', onClick: onUndo }, { label: 'Redo', shortcut: 'Ctrl+Y', onClick: onRedo }, { label: 'Duplicate selection', shortcut: 'Ctrl+D', onClick: onDuplicate }])}{menu('View', [{ label: 'Command palette', shortcut: 'Ctrl+P', onClick: onCommandPalette }, { label: 'Toggle grid', onClick: onToggleGrid }, { label: 'Toggle navigator', shortcut: 'Ctrl+Shift+1', onClick: onToggleNavigator }, { label: 'Toggle inspector', shortcut: 'Ctrl+Shift+2', onClick: onToggleInspector }])}{menu('Arrange', [{ label: 'Fit diagram', shortcut: 'F', onClick: onFit }, { label: 'Align selection', onClick: onAlign }])}{menu('Diagram', [{ label: 'Export SVG', onClick: onExportSvg }])}{menu('Help', [{ label: 'Keyboard shortcuts', onClick: onCommandPalette }, { label: 'About UML Studio', onClick: onAbout }], <CircleHelp size={13} />)}</div>
    <div className="topbar-actions"><button className="toolbar-button topbar-action" onClick={onNew}><FilePlus2 size={14} /> New</button><button className="toolbar-button topbar-action" onClick={onOpen}><FolderOpen size={14} /> Open</button><button className="toolbar-button primary topbar-action" onClick={onSave}><Save size={14} /> Save</button><button className="icon-button" onClick={onSaveAs} title="Save As" aria-label="Save As"><ArrowUpFromLine size={15} /></button><span className="topbar-divider" /><button className="icon-button" onClick={onUndo} title="Undo (Ctrl+Z)" aria-label="Undo"><Undo2 size={15} /></button><button className="icon-button" onClick={onRedo} title="Redo (Ctrl+Y)" aria-label="Redo"><Redo2 size={15} /></button></div>
    <div className="topbar-right"><button className="theme-button" onClick={onTheme} title={`Theme: ${theme}`} aria-label={`Theme: ${theme}`}>{theme === 'dark' ? <Moon size={14} /> : theme === 'light' ? <Sun size={14} /> : <Sparkles size={14} />}<span>{theme[0].toUpperCase() + theme.slice(1)}</span></button><button className="command-button" onClick={onCommandPalette} title="Command palette (Ctrl+P)" aria-label="Open command palette"><CommandIcon size={14} /><kbd>Ctrl P</kbd></button></div>
  </header>;
}
